version: '3.8'
services:
  web:
    build:
      context: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=challenge_dev
      - PGPORT=5432
      - PGHOST=db
    entrypoint:
      - "/bin/run.sh"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
